export type SVPosition = {
  customSpawningInformation?: string;
};

export type SPPosition = {
  customSpawningInformation?: string;
};

export type SGPosition = {
  zone?: string;
};

export type GDPosition = {
  train?: string;
  player?: string;
};

export type DSPosition = {
  station?: string;
  platform_group?: string;
};

export type QDPosition = {
  leg_1?: string;
  leg_2?: string;
  leg_3?: string;
  spawn_depot?: string;
};

export enum Operator {
  Airlink = "Airlink",
  Connect = "Stepford Connect",
  Express = "Stepford Express",
  Waterline = "Waterline",
  Metro = "Metro",
}

export enum NetworkManager {
  TfS = "Transport for Stepford",
  NationalRail = "National Rail",
  NetworkRail = "Network Rail",
}

export enum RouteType {
  SemiFast = 1,
  Stopping = 2,
  Empty = 3,
  HighPriority = 9,
}

export type Station = {
  name: string;
  operators: Operator[];
  managers: (Operator | NetworkManager)[];
  signal_zone: string[];
  electrification: boolean;
  dispatchable: boolean;
  dispatch_groups?: (number | string)[][];
  headcode?: string;
};

export const STATIONS: Record<string, Station> = {
  SAO: {
    name: "Airport Terminal 1",
    operators: [Operator.Airlink],
    managers: [Operator.Airlink],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: false,
  },
  SAX: {
    name: "Airport Terminal 2",
    operators: [Operator.Connect, Operator.Waterline, Operator.Airlink],
    managers: [Operator.Airlink],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
    headcode: "X",
  },
  SAZ: {
    name: "Airport Terminal 3",
    operators: [Operator.Airlink],
    managers: [Operator.Airlink],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "Z",
  },
  SAW: {
    name: "Airport West",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  AGP: {
    name: "Angel Pass",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  APK: {
    name: "Ashlan Park",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: false,
  },
  ALB: {
    name: "Aslockby",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["H"],
    electrification: false,
    dispatchable: false,
  },
  BAR: {
    name: "Barton",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
    headcode: "B",
  },
  BPK: {
    name: "Beaulieu Park",
    operators: [Operator.Metro],
    managers: [Operator.Metro],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  BCY: {
    name: "Beechley",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
    headcode: "C",
  },
  BEN: {
    name: "Benton",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Waterline,
      Operator.Express,
    ],
    managers: [NetworkManager.NationalRail],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [8, 9, 10, 11, 12, 13],
      [4, 5, 6, 7],
      [1, 2, 3],
    ],
    headcode: "B",
  },
  BNB: {
    name: "Benton Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
  },
  BRY: {
    name: "Berrilly",
    operators: [Operator.Connect, Operator.Metro, Operator.Airlink],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
    headcode: "Y",
  },
  BOD: {
    name: "Bodin",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  CSP: {
    name: "Cambridge Street Parkway",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  CLB: {
    name: "Carnalea Bridge",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["H"],
    electrification: false,
    dispatchable: false,
  },
  CHP: {
    name: "City Hospital",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  CON: {
    name: "Connolly",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "O",
  },
  COX: {
    name: "Coxly",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  CXN: {
    name: "Coxly Newtown",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  EBR: {
    name: "East Berrilly",
    operators: [Operator.Metro],
    managers: [Operator.Metro],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  EDQ: {
    name: "Eden Quay",
    operators: [Operator.Waterline, Operator.Express],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  EDG: {
    name: "Edgemead",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  EMJ: {
    name: "Elsemere Junction",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [Operator.Airlink, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
  },
  EMP: {
    name: "Elsemere Pond",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: false,
  },
  EFD: {
    name: "Esterfield",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["G"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, "4B"]],
    headcode: "Q",
  },
  FRD: {
    name: "Faraday Road",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
  },
  FAR: {
    name: "Farleigh",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["G"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
    headcode: "J",
  },
  FAY: {
    name: "Faymere",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  FNQ: {
    name: "Financial Quarter",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  FWY: {
    name: "Four Ways",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["J"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [["A", "B"]],
  },
  GNS: {
    name: "Greenslade",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
    headcode: "G",
  },
  HHG: {
    name: "Hampton Hargate",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: false,
  },
  HPK: {
    name: "Hemdon Park",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  HTR: {
    name: "Houghton Rake",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["A"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  JST: {
    name: "James Street",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["G"],
    electrification: true,
    dispatchable: false,
  },
  LTC: {
    name: "Leighton City",
    operators: [Operator.Connect, Operator.Express],
    managers: [NetworkManager.NationalRail],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [1, 2, 3, 4],
      [5, 6],
    ],
    headcode: "T",
  },
  LSR: {
    name: "Leighton Stepford Road",
    operators: [Operator.Connect, Operator.Airlink, Operator.Express],
    managers: [Operator.Express],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [1, 2, 3],
      [4, 5],
    ],
    headcode: "R",
  },
  LTW: {
    name: "Leighton West",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: false,
    headcode: "K",
  },
  LYN: {
    name: "Llyn-by-the-Sea",
    operators: [Operator.Connect, Operator.Express],
    managers: [NetworkManager.NationalRail],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [0, 1, 2, 3, 4, 5, 6],
      [7, 8, 9, 10, 11],
    ],
    headcode: "L",
  },
  MLC: {
    name: "Millcastle",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
  },
  MRC: {
    name: "Millcastle Racecourse",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: false,
  },
  MGT: {
    name: "Morganstown",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Waterline,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [NetworkManager.NationalRail],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4, 5, 6]],
    headcode: "M",
  },
  MGD: {
    name: "Morganstown Docks",
    operators: [Operator.Metro, Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: false,
    dispatchable: false,
  },
  NHW: {
    name: "New Harrow",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["B"],
    electrification: true,
    dispatchable: false,
  },
  NRY: {
    name: "Newry",
    operators: [Operator.Waterline, Operator.Express],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "N",
  },
  NRH: {
    name: "Newry Harbour",
    operators: [Operator.Waterline, Operator.Express],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
    headcode: "H",
  },
  NSE: {
    name: "Northshore",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Express],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
  },
  PBN: {
    name: "Port Benton",
    operators: [Operator.Connect, Operator.Metro, Operator.Waterline],
    managers: [Operator.Connect],
    signal_zone: ["F"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "P",
  },
  RLB: {
    name: "Rayleigh Bay",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signal_zone: ["H"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "R",
  },
  RCP: {
    name: "Rocket Parade",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: false,
  },
  RDV: {
    name: "Rosedale Village",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["G"],
    electrification: true,
    dispatchable: false,
  },
  SHB: {
    name: "St Helens Bridge",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [NetworkManager.TfS, NetworkManager.NationalRail],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [1, 2, 3, 4, 5],
      [6, 7],
    ],
    headcode: "I",
  },
  STL: {
    name: "Starryloch",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: false,
  },
  SAC: {
    name: "Stepford Airport Central",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Airlink, NetworkManager.NationalRail],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [3, 4, 5, 6],
      [0, 1, 2],
    ],
    headcode: "A",
  },
  SAP: {
    name: "Stepford Airport Parkway",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Airlink],
    signal_zone: ["C"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [1, 2],
      [3, 4, 5],
    ],
    headcode: "P",
  },
  SCN: {
    name: "Stepford Central",
    operators: [
      Operator.Connect,
      Operator.Metro,
      Operator.Airlink,
      Operator.Express,
    ],
    managers: [NetworkManager.TfS, NetworkManager.NationalRail],
    signal_zone: ["A", "J"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      ["A", "B", "C", "D"],
      [12, 13, 14, 15],
      [10, 11],
    ],
    headcode: "S",
  },
  SCE: {
    name: "Stepford East",
    operators: [Operator.Connect, Operator.Metro, Operator.Airlink],
    managers: [NetworkManager.TfS, NetworkManager.NationalRail],
    signal_zone: ["A", "J"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [
      [1, 2, 3, 4],
      ["A", "B", "C", "D"],
      [5, 6, 7, 8],
    ],
  },
  SHS: {
    name: "Stepford High Street",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["J"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [["A", "B", "C", "D"]],
  },
  UFC: {
    name: "Stepford UFC",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
    headcode: "U",
  },
  SCV: {
    name: "Stepford Victoria",
    operators: [Operator.Connect, Operator.Metro],
    managers: [NetworkManager.TfS, NetworkManager.NationalRail],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4, 5, 6]],
    headcode: "V",
  },
  USL: {
    name: "Upper Staploe",
    operators: [Operator.Connect],
    managers: [Operator.Metro],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: false,
  },
  WTN: {
    name: "Water Newton",
    operators: [Operator.Connect, Operator.Airlink],
    managers: [Operator.Connect],
    signal_zone: ["D"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
  },
  WBN: {
    name: "West Benton",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  WST: {
    name: "Westercoast",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Connect],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  WYV: {
    name: "Westwyvern",
    operators: [Operator.Connect, Operator.Express],
    managers: [Operator.Express],
    signal_zone: ["E"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3, 4]],
    headcode: "W",
  },
  WHF: {
    name: "Whitefield",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["A"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "F",
  },
  WFL: {
    name: "Whitefield Lido",
    operators: [Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
  WNG: {
    name: "Whitney Green",
    operators: [Operator.Waterline],
    managers: [Operator.Waterline],
    signal_zone: ["F"],
    electrification: true,
    dispatchable: false,
  },
  WFD: {
    name: "Willowfield",
    operators: [Operator.Connect, Operator.Metro],
    managers: [Operator.Metro, NetworkManager.TfS],
    signal_zone: ["A"],
    electrification: true,
    dispatchable: true,
    dispatch_groups: [[1, 2, 3]],
    headcode: "D",
  },
  WHL: {
    name: "Woodhead Lane",
    operators: [Operator.Connect],
    managers: [Operator.Connect],
    signal_zone: ["A"],
    electrification: false,
    dispatchable: true,
    dispatch_groups: [[1, 2]],
  },
};

export type SignalZone = {
  name: string;
  desk_location: string;
  stations: string[];
};

export const SIGNAL_ZONES: Record<string, SignalZone> = {
  A: {
    name: "Stepford Zone",
    desk_location: "SCN",
    stations: [
      "WFD",
      "HPK",
      "BCY",
      "SCV",
      "FNQ",
      "CHP",
      "SCN",
      "SCE",
      "WFL",
      "UFC",
      "WHL",
      "HTR",
      "WHF",
    ],
  },
  B: {
    name: "St Helens Bridge/Coxly/Beaulieu Zone",
    desk_location: "BPK",
    stations: [
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
      "EBR",
      "BPK",
    ],
  },
  C: {
    name: "Airport Zone",
    desk_location: "SAC",
    stations: ["SAZ", "SAX", "SAO", "SAC", "SAW", "SAP"],
  },
  D: {
    name: "Leighton Zone",
    desk_location: "SCN",
    stations: ["MGT", "HHG", "USL", "WTN", "RCP", "LSR", "LTC", "LTW"],
  },
  E: {
    name: "Llyn-by-the-Sea Zone",
    desk_location: "LYN",
    stations: ["LYN", "NSE", "STL", "WYV", "MLC", "MRC", "WST", "FAY", "EDG"],
  },
  F: {
    name: "Benton Zone",
    desk_location: "BEN",
    stations: [
      "NRH",
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "BEN",
      "CON",
      "APK",
      "CSP",
      "PBN",
      "MGD",
      "WNG",
      "GNS",
    ],
  },
  G: {
    name: "Esterfield Zone",
    desk_location: "SCN",
    stations: ["JST", "FAR", "RDV", "EFD"],
  },
  H: {
    name: "Rayleigh Bay Zone",
    desk_location: "RLB",
    stations: ["ALB", "CLB", "RLB"],
  },
  J: {
    name: "Metro Core Zone",
    desk_location: "SHS",
    stations: ["SCN", "FWY", "SCE", "SHS"],
  },
};

export type Route = {
  type: RouteType;
  operator: Operator;
  inbound_destination: string;
  outbound_destination: string;
  inbound_route: string[];
  outbound_route: string[];
  electric_trains: boolean;
  notes?: string;
  alternate_name?: string;
};

export const ROUTES: Record<string, Route> = {
  R001: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCN",
    inbound_route: [
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAC",
    outbound_route: [
      "SCN",
      "SCE",
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "SAP",
      "SAC",
    ],
    electric_trains: true,
    notes: "Class 68, 156, and 444 not allowed",
  },
  R002: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCN",
    inbound_route: [
      "PBN",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
    ],
    outbound_destination: "PBN",
    outbound_route: [
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "PBN",
    ],
    electric_trains: true,
  },
  R003: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCN",
    inbound_route: [
      "LTC",
      "LSR",
      "RCP",
      "WTN",
      "USL",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LTC",
    outbound_route: [
      "SCN",
      "SCE",
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "USL",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R004: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SHB",
    inbound_route: [
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "WTN",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
    ],
    outbound_destination: "EDG",
    outbound_route: [
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R005: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SCV",
    inbound_route: [
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "SAC",
    outbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "SAP",
      "SAC",
    ],
    electric_trains: true,
    notes: "Class 68, 156, and 444 not allowed",
  },
  R006: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: [
      "PBN",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "PBN",
    outbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "PBN",
    ],
    electric_trains: true,
  },
  R007: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SCN",
    inbound_route: [
      "MGT",
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "SCN",
      "SCE",
      "SHB",
      "EMJ",
      "BRY",
      "Berrily Depot (EB)",
      "MGT",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R008: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: [
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "FWY",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "BRY",
    outbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
    ],
    electric_trains: true,
  },
  R009: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SCV",
    inbound_route: [
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "RCP",
      "WTN",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "Beechley Sidings",
      "SCV",
    ],
    outbound_destination: "EDG",
    outbound_route: [
      "SCV",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R010: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRY",
    inbound_route: [
      "GNS",
      "WNG",
      "MGD",
      "PBN",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
    ],
    outbound_destination: "GNS",
    outbound_route: [
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "PBN",
      "MGD",
      "Whitney Green Depot",
      "WNG",
      "GNS",
    ],
    electric_trains: true,
  },
  R011: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRY",
    inbound_route: [
      "CON",
      "APK",
      "CSP",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
    ],
    outbound_destination: "CON",
    outbound_route: [
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "CSP",
      "APK",
      "CON",
    ],
    electric_trains: true,
  },
  R012: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRH",
    inbound_route: [
      "CON",
      "APK",
      "CSP",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
      "NRH",
    ],
    outbound_destination: "CON",
    outbound_route: [
      "NRH",
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "CSP",
      "APK",
      "CON",
    ],
    electric_trains: false,
  },
  R013: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "BEN",
    inbound_route: ["GNS", "WNG", "MGD", "PBN", "BEN"],
    outbound_destination: "GNS",
    outbound_route: [
      "Benton Siding",
      "BEN",
      "PBN",
      "MGD",
      "Whitney Green Depot",
      "WNG",
      "GNS",
    ],
    electric_trains: true,
  },
  R014: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRY",
    inbound_route: [
      "EFD",
      "Esterfield Mainline Depot",
      "FAR",
      "SAW",
      "CSP",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Nery Siding",
      "NRY",
    ],
    outbound_destination: "EFD",
    outbound_route: [
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "CSP",
      "SAW",
      "Farleigh Depot (Road 2)",
      "FAR",
      "Esterfield Station Depot",
      "EFD",
    ],
    electric_trains: true,
  },
  R015: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "BEN",
    inbound_route: ["Morganstown Siding", "MGT", "MGD", "PBN", "BEN"],
    outbound_destination: "MGT",
    outbound_route: ["Benton Siding", "BEN", "PBN", "MGD", "MGT"],
    electric_trains: false,
    notes: "Only 2 car long trains",
    alternate_name: "Morganstown Shuttle",
  },
  R016: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "BEN",
    inbound_route: [
      "EFD",
      "Esterfield Mainline Depot",
      "RDV",
      "FAR",
      "JST",
      "SAW",
      "CSP",
      "BEN",
    ],
    outbound_destination: "EFD",
    outbound_route: [
      "Benton Siding",
      "BEN",
      "CSP",
      "SAW",
      "Farleigh Depot (Road 2)",
      "JST",
      "FAR",
      "RDV",
      "Esterfield Station Depot",
      "EFD",
    ],
    electric_trains: true,
  },
  R017: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRY",
    inbound_route: [
      "SAX",
      "SAW",
      "CSP",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "CSP",
      "SAW",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
  },
  R018: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRH",
    inbound_route: [
      "FAR",
      "JST",
      "SAW",
      "CSP",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
      "NRH",
    ],
    outbound_destination: "FAR",
    outbound_route: [
      "NRH",
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "CSP",
      "SAW",
      "Farleigh Depot (Road 2)",
      "JST",
      "FAR",
    ],
    electric_trains: false,
  },
  R019: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "BEN",
    inbound_route: ["CON", "APK", "CSP", "BEN"],
    outbound_destination: "CON",
    outbound_route: ["Benton Siding", "BEN", "CSP", "APK", "CON"],
    electric_trains: true,
  },
  R020: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCN",
    inbound_route: [
      "WHF",
      "Whitefield Siding",
      "HTR",
      "WHL",
      "Woodhead Lane SB Depot",
      "UFC",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "WHF",
    outbound_route: [
      "SCN",
      "SCE",
      "UFC",
      "Woodhead Lane NB Depot",
      "WHL",
      "HTR",
      "WHF",
    ],
    electric_trains: false,
    notes: "Class 156 not allowed",
  },
  R021: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCN",
    inbound_route: [
      "Woodhead Lane SB Depot",
      "UFC",
      "WFL",
      "SHS",
      "SCE",
      "FWY",
      "SCN",
    ],
    outbound_destination: "UFC",
    outbound_route: ["SCN", "FWY", "SCE", "SHS", "WFL", "UFC"],
    electric_trains: true,
  },
  R022: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "BCY",
    inbound_route: [
      "WHF",
      "Whitefield Siding",
      "WHL",
      "Woodhead Lane SB Depot",
      "UFC",
      "SCE",
      "Stepford Depot",
      "SCN",
      "Beechley",
    ],
    outbound_destination: "WHF",
    outbound_route: [
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "UFC",
      "Woodhead Lane NB Depot",
      "WHL",
      "WHF",
    ],
    electric_trains: false,
    notes: "Class 156 not allowed",
  },
  R023: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: [
      "Woodhead Lane SB Depot",
      "UFC",
      "WFL",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "UFC",
    outbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "WFL",
      "UFC",
    ],
    electric_trains: true,
  },
  R024: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "NSE",
      "STL",
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTC",
      "LSR",
      "RCP",
      "WTN",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WST",
      "STL",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
  },
  R025: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SHB",
    inbound_route: [
      "WYV",
      "MLC",
      "MRC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTC",
      "LSR",
      "RCP",
      "USL",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
    ],
    outbound_destination: "WYV",
    outbound_route: [
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "USL",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MRC",
      "MLC",
      "WYV",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R026: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "SCV",
    inbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "WTN",
      "HHG",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "Beechley Sidings",
      "SCV",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCV",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
    notes: "Class 68 and 444 only",
  },
  R027: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCN",
    inbound_route: [
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
    ],
    outbound_destination: "BRY",
    outbound_route: [
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
    ],
    electric_trains: true,
  },
  R028: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: [
      "WFD",
      "Willowfield Depot",
      "HPK",
      "BCY",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "WFD",
    outbound_route: ["SCV", "FNQ", "BCY", "HPK", "Willowfield Depot", "WFD"],
    electric_trains: true,
  },
  R029: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: ["BCY", "Beechley Sidings", "FNQ", "SCV"],
    outbound_destination: "BCY",
    outbound_route: ["SCV", "FNQ", "BCY"],
    electric_trains: true,
  },
  R030: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "WFD",
    inbound_route: [
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "HPK",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "BRY",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "HPK",
      "BCY",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
    ],
    electric_trains: true,
  },
  R031: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "WFD",
    inbound_route: [
      "Woohead Lane SB Depot",
      "UFC",
      "WFL",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "BCY",
      "HPK",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "UFC",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "HPK",
      "BCY",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "WFL",
      "UFC",
    ],
    electric_trains: true,
  },
  R032: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "WFD",
    inbound_route: [
      "PBN",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "BCY",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "PBN",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "PBN",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R033: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "BCY",
    inbound_route: [
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "BCY",
    ],
    outbound_destination: "SAC",
    outbound_route: [
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "SAP",
      "SAC",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R034: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BCY",
    inbound_route: [
      "MGT",
      "BPK",
      "EBR",
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "BCY",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "BCY",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
      "Berrily Depot (EB)",
      "EBR",
      "BPK",
      "MGT",
    ],
    electric_trains: true,
  },
  R035: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "WFD",
    inbound_route: [
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTC",
      "LSR",
      "WTN",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "BCY",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "WYV",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WYV",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R036: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "WFD",
    inbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "WTN",
      "HHG",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "BCY",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "HHG",
      "Hampton Hargate Siding",
      "WTN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
    notes: "Class 68 and 444 only",
  },
  R037: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "LTC",
    inbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTC",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "LTC",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
  },
  R038: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "LTC",
    inbound_route: [
      "WYV",
      "MLC",
      "MRC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTC",
    ],
    outbound_destination: "WYV",
    outbound_route: [
      "LTC",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MRC",
      "MLC",
      "WYV",
    ],
    electric_trains: true,
  },
  R039: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "BEN",
    inbound_route: ["LTC", "LSR", "RCP", "WTN", "USL", "HHG", "BNB", "BEN"],
    outbound_destination: "LTC",
    outbound_route: [
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "USL",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
    ],
    electric_trains: true,
  },
  R040: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "EDG",
    inbound_route: [
      "LYN",
      "NSE",
      "STL",
      "WYv",
      "MLC",
      "MRC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MRC",
      "MLC",
      "WYV",
      "STL",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
  },
  R041: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "LYN",
    inbound_route: ["Faymere Green NB Depot", "EDG", "LTW"],
    outbound_destination: "EDG",
    outbound_route: ["LTW", "EDG"],
    electric_trains: true,
  },
  R042: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "LTW",
    inbound_route: [
      "LYN",
      "NSE",
      "STL",
      "WYV",
      "MLC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "LTW",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "LTW",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MLC",
      "WYV",
      "STL",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
  },
  R043: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "LTW",
    inbound_route: ["Leighton Depot", "LTC", "LTW"],
    outbound_destination: "LTC",
    outbound_route: ["LTW", "LTC"],
    electric_trains: true,
  },
  R044: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "BEN",
    inbound_route: [
      "LTW",
      "LTC",
      "LSR",
      "RCP",
      "WTN",
      "USL",
      "HHG",
      "BNB",
      "BEN",
    ],
    outbound_destination: "LTW",
    outbound_route: [
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "USL",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
      "LTW",
    ],
    electric_trains: true,
  },
  R045: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCV",
    inbound_route: [
      "LTC",
      "LSR",
      "RCP",
      "WTN",
      "USL",
      "HHG",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "Beechley Sidings",
      "SCV",
    ],
    outbound_destination: "LTC",
    outbound_route: [
      "SCV",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "HHG",
      "Hampton Hargate Siding",
      "USL",
      "WTN",
      "RCP",
      "Leighton Depot",
      "LSR",
      "LTC",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R046: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SCV",
    inbound_route: [
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "BNB",
      "Benton Bridge",
      "BEN",
      "COX",
      "BOD",
      "SHB",
      "SCE",
      "Stepford Depot",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "SCV",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "SCV",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "SCE",
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "SAP",
      "SAC",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
    notes: "Class 68, 156, and 444 not allowed",
  },
  R047: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SHB",
    inbound_route: ["PBN", "Benton Depot", "BEN", "COX", "BOD", "AGP", "SHB"],
    outbound_destination: "PBN",
    outbound_route: [
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "PBN",
    ],
    electric_trains: true,
  },
  R048: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "SHB",
    inbound_route: [
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "BNB",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "SHB",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "SHB",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "BNB",
      "SAP",
      "SAC",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
    notes: "Class 156 not allowed",
  },
  R049: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "RLB",
    inbound_route: ["Faymere Green NB Depot", "EDG", "ALB", "CLB", "RLB"],
    outbound_destination: "EDG",
    outbound_route: ["RLB", "CLB", "ALB", "EDG"],
    electric_trains: false,
  },
  R050: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "RLB",
    inbound_route: [
      "LYN",
      "NSE",
      "STL",
      "WYV",
      "MLC",
      "MRC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "ALB",
      "CLB",
      "RLB",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "RLB",
      "CLB",
      "ALB",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MRC",
      "MLC",
      "WYV",
      "STL",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
  },
  R051: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SAC",
    inbound_route: ["Farleigh Depot (Road 11)", "SAC", "Stepford Depot", "SCN"],
    outbound_destination: "SCN",
    outbound_route: ["SCN", "Airport Parkway Siding", "SAC"],
    electric_trains: true,
  },
  R052: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "SCN",
      "Airport Parkway",
      "SAC",
      "SAO",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
  },
  R053: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "Airport Parkway Depot",
      "MGT",
      "EMJ",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "SCN",
      "SCE",
      "EMJ",
      "MGT",
      "Airport Parkway Siding",
      "SAC",
      "SAO",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
  },
  R054: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "Airport Parkway Depot",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAC",
    outbound_route: [
      "SCN",
      "SHB",
      "BRY",
      "Airport Parkway Siding",
      "SAP",
      "SAC",
    ],
    electric_trains: true,
  },
  R055: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "SAZ",
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "Airport Parkway Depot",
      "SCE",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAZ",
    outbound_route: [
      "SCN",
      "SCE",
      "Airport Parkway Siding",
      "SAP",
      "SAC",
      "Farleigh Depot (Road 17)",
      "SAX",
      "SAZ",
    ],
    electric_trains: true,
  },
  R056: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SAC",
    inbound_route: ["LSR", "Airport Parkway Siding", "SAP", "SAC"],
    outbound_destination: "LSR",
    outbound_route: [
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "Leighton Depot",
      "LSR",
    ],
    electric_trains: true,
  },
  R057: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SAZ",
    inbound_route: [
      "LSR",
      "WTN",
      "SAC",
      "Farleigh Depot (Road 17)",
      "SAX",
      "SAZ",
    ],
    outbound_destination: "LSR",
    outbound_route: [
      "SAZ",
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "Airport Parkway Depot",
      "WTN",
      "Leighton Depot",
      "LSR",
    ],
    electric_trains: true,
  },
  R058: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "SAZ",
      "Farleigh Depot (Road 17)",
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "Airport Parkway Depot",
      "MGT",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAZ",
    outbound_route: [
      "SCN",
      "SHB",
      "MGT",
      "Airport Parkway Siding",
      "SAC",
      "SAO",
      "SAZ",
    ],
    electric_trains: true,
  },
  R059: {
    type: RouteType.SemiFast,
    operator: Operator.Airlink,
    inbound_destination: "SCN",
    inbound_route: [
      "SAX",
      "Farleigh Depot (Road 11)",
      "SAC",
      "SAP",
      "Airport Parkway Depot",
      "EMJ",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "SAX",
    outbound_route: [
      "SCN",
      "SHB",
      "EMJ",
      "Airport Parkway Siding",
      "SAP",
      "SAC",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
  },
  R060: {
    type: RouteType.HighPriority,
    operator: Operator.Airlink,
    inbound_destination: "SAP",
    inbound_route: ["SAZ", "Farleigh Depot (Road 11)", "SAC", "SAP"],
    outbound_destination: "SAX",
    outbound_route: [
      "Airport Parkway Siding",
      "SAP",
      "SAC",
      "SAO",
      "SAZ",
      "Farleigh Depot (Road 17)",
      "SAX",
    ],
    electric_trains: true,
    notes: "Class 345 only",
    alternate_name: "Terminals Shuttle",
  },
  R075: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: ["Benton Depot", "BEN", "Stepford Depot", "SCN"],
    outbound_destination: "BEN",
    outbound_route: ["SCN", "Coxly Bypass Siding", "BEN"],
    electric_trains: true,
    alternate_name: "Benton Express (fast)",
  },
  R076: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LTC",
      "LSR",
      "Benton Depot",
      "BEN",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LTC",
    outbound_route: [
      "SCN",
      "SHB",
      "Coxly Bypass Siding",
      "BEN",
      "Leighton Depot",
      "LSR",
      "LTC",
    ],
    electric_trains: true,
    alternate_name: "Leighton Express",
  },
  R077: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "Benton Depot",
      "BEN",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCN",
      "SHB",
      "Coxly Bypass Siding",
      "BEN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "Faymere Green SB Depot",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
    alternate_name: "Llyn via Benton",
  },
  R078: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "WYV",
      "Faymere Green NB Depot",
      "LTC",
      "LSR",
      "Benton Depot",
      "BEN",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCN",
      "Coxly Bypass Siding",
      "BEN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "Faymere Green SB Depot",
      "WYV",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
    alternate_name: "Llyn via Benton (fast)",
  },
  R079: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: ["Benton Depot", "BEN", "SHB", "Stepford Depot", "SCN"],
    outbound_destination: "BEN",
    outbound_route: ["SCN", "SHB", "Coxly Bypass Siding", "BEN"],
    electric_trains: true,
    alternate_name: "Benton Express",
  },
  R080: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "Faymere Green NB Depot",
      "LTC",
      "LSR",
      "MGT",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCN",
      "SHB",
      "MGT",
      "Leighton Depot",
      "LSR",
      "LTC",
      "Faymere Green SB Depot",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
    alternate_name: "Llyn via Morganstown (fast)",
  },
  R081: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "Faymere Green NB Depot",
      "LTC",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: ["SCN", "Leighton Depot", "LTC", "Northshore Depot", "LYN"],
    alternate_name: "Llyn (super fast)",
    electric_trains: true,
  },
  R082: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "WYV",
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "MGT",
      "EMJ",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "WYV",
    outbound_route: [
      "SCN",
      "EMJ",
      "MGT",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "Faymere Green SB Depot",
      "WYV",
    ],
    alternate_name: "Westwyvern Express",
    electric_trains: true,
  },
  R083: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "NRY",
    inbound_route: [
      "LYN",
      "NSE",
      "WST",
      "Faymere Green NB Depot",
      "LTC",
      "LSR",
      "MGT",
      "BEN",
      "Newry Siding",
      "NRY",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "NRY",
      "BEN",
      "MGT",
      "Leighton Depot",
      "LSR",
      "LTC",
      "Faymere Green SB Depot",
      "WST",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
  },
  R084: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "NRH",
    inbound_route: [
      "LYN",
      "WYV",
      "Faymere Green NB Depot",
      "LTC",
      "BEN",
      "Newry Siding",
      "NRY",
      "NRH",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "NRH",
      "NRY",
      "BEN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "Faymere Green SB Depot",
      "WYV",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
  },
  R085: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "BEN",
    inbound_route: [
      "LYN",
      "NSE",
      "Faymere Green NB Depot",
      "LTC",
      "LSR",
      "MGT",
      "BEN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "BEN",
      "MGT",
      "Leighton Depot",
      "LSR",
      "LTC",
      "Faymere Green SB Depot",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: false,
    notes: "Class 180, 221 (double), and 800/2 (double) not allowed",
  },
  R086: {
    type: RouteType.HighPriority,
    operator: Operator.Express,
    inbound_destination: "NRY",
    inbound_route: ["LTC", "LSR", "BEN", "Faraday Road Depot", "EDQ", "NRY"],
    outbound_destination: "LTC",
    outbound_route: ["NRY", "EDQ", "Leighton Depot", "LSR", "LTC"],
    electric_trains: true,
    notes: "Class 220 (single), 221 (single) and 800/2 (single) only",
  },
  R087: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "LYN",
    inbound_route: [
      "RLB",
      "EDG",
      "Faymere Green SB Depot",
      "WYV",
      "NSE",
      "Northshore Depot",
      "LYN",
    ],
    outbound_destination: "RLB",
    outbound_route: [
      "LYN",
      "NSE",
      "WYV",
      "Faymere Green NB Depot",
      "EDG",
      "RLB",
    ],
    electric_trains: false,
    alternate_name: "Rayleigh Bay Express",
  },
  R088: {
    type: RouteType.SemiFast,
    operator: Operator.Express,
    inbound_destination: "SCN",
    inbound_route: [
      "LYN",
      "WST",
      "Faymere Green NB Depot",
      "EDG",
      "LTC",
      "LSR",
      "Benton Depot",
      "BEN",
      "SHB",
      "Stepford Depot",
      "SCN",
    ],
    outbound_destination: "LYN",
    outbound_route: [
      "SCN",
      "SHB",
      "Coxly Bypass Siding",
      "BEN",
      "Leighton Depot",
      "LSR",
      "LTC",
      "EDG",
      "Faymere Green SB Depot",
      "WST",
      "Northshore Depot",
      "LYN",
    ],
    electric_trains: true,
    alternate_name: "Llyn via Benton (Westercoast Express)",
  },
  R100: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "RLB",
    inbound_route: ["LTW", "Leighton Depot", "EDG", "ALB", "CLB", "RLB"],
    outbound_destination: "LTW",
    outbound_route: [
      "RLB",
      "CLB",
      "ALB",
      "EDG",
      "Faymere Green NB Depot",
      "LTW",
    ],
    electric_trains: false,
  },
  R101: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "RLB",
    inbound_route: ["Leighton Depot", "LTC", "EDG", "ALB", "CLB", "RLB"],
    outbound_destination: "LTC",
    outbound_route: ["RLB", "CLB", "ALB", "EDG", "LTC"],
    electric_trains: false,
  },
  R102: {
    type: RouteType.Stopping,
    operator: Operator.Connect,
    inbound_destination: "RLB",
    inbound_route: [
      "WYV",
      "MLC",
      "MRC",
      "WST",
      "Faymere Green NB Depot",
      "FAY",
      "EDG",
      "ALB",
      "CLB",
      "RLB",
    ],
    outbound_destination: "WYV",
    outbound_route: [
      "RLB",
      "CLB",
      "ALB",
      "EDG",
      "FAY",
      "Faymere Green SB Depot",
      "WST",
      "MRC",
      "MLC",
      "WYV",
    ],
    electric_trains: false,
    notes: "Class 156 only",
  },
  R103: {
    type: RouteType.SemiFast,
    operator: Operator.Connect,
    inbound_destination: "WFD",
    inbound_route: [
      "WHF",
      "Whitefield Siding",
      "HHR",
      "WHL",
      "Woodhead Lane SB Depot",
      "UFC",
      "SCE",
      "Stepford Depot",
      "SCN",
      "BCY",
      "Willowfield Depot",
      "WFD",
    ],
    outbound_destination: "WHF",
    outbound_route: [
      "WFD",
      "Willowfield Depot",
      "BCY",
      "Beechley Sidings",
      "SCN",
      "SCE",
      "UFC",
      "Woodhead Lane NB Depot",
      "WHL",
      "HHG",
      "WHF",
    ],
    electric_trains: false,
    notes: "Class 156 not allowed",
  },
  R120: {
    type: RouteType.Stopping,
    operator: Operator.Waterline,
    inbound_destination: "NRH",
    inbound_route: [
      "Morganstown Siding",
      "MGT",
      "MGD",
      "PBN",
      "BEN",
      "WBN",
      "Faraday Road Depot",
      "FRD",
      "EDQ",
      "Newry Siding",
      "NRY",
      "NRH",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "NRH",
      "NRY",
      "EDQ",
      "FRD",
      "WBN",
      "Benton Siding",
      "BEN",
      "PBN",
      "MGD",
      "MGT",
    ],
    electric_trains: false,
    notes: "2 car max",
  },
  R130: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SCN",
    inbound_route: [
      "MGT",
      "BPK",
      "EBR",
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
      "Berrily Depot (EB)",
      "EBR",
      "BPK",
      "MGT",
    ],
    electric_trains: true,
  },
  R131: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "SHB",
    inbound_route: [
      "MGT",
      "BPK",
      "EBR",
      "Berrily Depot (WB)",
      "BRY",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BRY",
      "Berrily Depot (EB)",
      "EBR",
      "BPK",
      "MGT",
    ],
    electric_trains: true,
  },
  R132: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BAR",
    inbound_route: [
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "AGP",
      "BOD",
      "CXN",
      "BAR",
    ],
    outbound_destination: "SCN",
    outbound_route: [
      "BAR",
      "Berrily Depot (WB)",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
    ],
    electric_trains: true,
  },
  R133: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BAR",
    inbound_route: [
      "WFD",
      "Willowfield Depot",
      "HPK",
      "BCY",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "AGP",
      "BOD",
      "CXN",
      "BAR",
    ],
    outbound_destination: "WFD",
    outbound_route: [
      "BAR",
      "Berrily Depot (WB)",
      "EMJ",
      "EMP",
      "NHW",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "BCY",
      "HPK",
      "Willowfield Depot",
      "WFD",
    ],
    electric_trains: true,
  },
  R134: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BAR",
    inbound_route: ["SHB", "AGP", "BOD", "CXN", "BAR"],
    outbound_destination: "SHB",
    outbound_route: ["BAR", "Berrily Depot (WB)", "EMJ", "EMP", "NHW", "SHB"],
    electric_trains: true,
  },
  R135: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BAR",
    inbound_route: [
      "BCY",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BAR",
    ],
    outbound_destination: "BCY",
    outbound_route: [
      "BAR",
      "CXN",
      "BOD",
      "AGP",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "BCY",
    ],
    electric_trains: true,
  },
  R136: {
    type: RouteType.Stopping,
    operator: Operator.Metro,
    inbound_destination: "BAR",
    inbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "NHW",
      "EMP",
      "EMJ",
      "BAR",
    ],
    outbound_destination: "SCV",
    outbound_route: [
      "BAR",
      "CXN",
      "BOD",
      "AGP",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    electric_trains: true,
  },
  R137: {
    type: RouteType.HighPriority,
    operator: Operator.Metro,
    inbound_destination: "SCV",
    inbound_route: [
      "Morganstown Siding",
      "MGT",
      "MGD",
      "PBN",
      "Benton Depot",
      "BEN",
      "COX",
      "BOD",
      "AGP",
      "SHB",
      "SHS",
      "Stepford Depot",
      "SCE",
      "FWY",
      "SCN",
      "CHP",
      "Beechley Sidings",
      "FNQ",
      "SCV",
    ],
    outbound_destination: "MGT",
    outbound_route: [
      "SCV",
      "FNQ",
      "Beechley Sidings",
      "CHP",
      "SCN",
      "FWY",
      "SCE",
      "SHS",
      "SHB",
      "AGP",
      "BOD",
      "Coxly Station Siding",
      "COX",
      "Coxly Bypass Siding",
      "BEN",
      "PBN",
      "MGD",
      "MGT",
    ],
    electric_trains: false,
    notes: "Class 756 only",
  },
};
